//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formulario.SWParticipante {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="SWParticipante.SWParticipante")]
    public interface SWParticipante {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWParticipante/helloRequest", ReplyAction="http://ws/SWParticipante/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Formulario.SWParticipante.helloResponse hello(Formulario.SWParticipante.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWParticipante/helloRequest", ReplyAction="http://ws/SWParticipante/helloResponse")]
        System.Threading.Tasks.Task<Formulario.SWParticipante.helloResponse> helloAsync(Formulario.SWParticipante.helloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWParticipante/EstadisticasRequest", ReplyAction="http://ws/SWParticipante/EstadisticasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Formulario.SWParticipante.EstadisticasResponse Estadisticas(Formulario.SWParticipante.EstadisticasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWParticipante/EstadisticasRequest", ReplyAction="http://ws/SWParticipante/EstadisticasResponse")]
        System.Threading.Tasks.Task<Formulario.SWParticipante.EstadisticasResponse> EstadisticasAsync(Formulario.SWParticipante.EstadisticasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWParticipante/crearParticipanteRequest", ReplyAction="http://ws/SWParticipante/crearParticipanteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Formulario.SWParticipante.crearParticipanteResponse crearParticipante(Formulario.SWParticipante.crearParticipanteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWParticipante/crearParticipanteRequest", ReplyAction="http://ws/SWParticipante/crearParticipanteResponse")]
        System.Threading.Tasks.Task<Formulario.SWParticipante.crearParticipanteResponse> crearParticipanteAsync(Formulario.SWParticipante.crearParticipanteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWParticipante/listarParticipantesRequest", ReplyAction="http://ws/SWParticipante/listarParticipantesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Formulario.SWParticipante.listarParticipantesResponse listarParticipantes(Formulario.SWParticipante.listarParticipantesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWParticipante/listarParticipantesRequest", ReplyAction="http://ws/SWParticipante/listarParticipantesResponse")]
        System.Threading.Tasks.Task<Formulario.SWParticipante.listarParticipantesResponse> listarParticipantesAsync(Formulario.SWParticipante.listarParticipantesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWParticipante/actualizarParticipanteRequest", ReplyAction="http://ws/SWParticipante/actualizarParticipanteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Formulario.SWParticipante.actualizarParticipanteResponse actualizarParticipante(Formulario.SWParticipante.actualizarParticipanteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWParticipante/actualizarParticipanteRequest", ReplyAction="http://ws/SWParticipante/actualizarParticipanteResponse")]
        System.Threading.Tasks.Task<Formulario.SWParticipante.actualizarParticipanteResponse> actualizarParticipanteAsync(Formulario.SWParticipante.actualizarParticipanteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWParticipante/filtrarParticipantePorApodoRequest", ReplyAction="http://ws/SWParticipante/filtrarParticipantePorApodoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Formulario.SWParticipante.filtrarParticipantePorApodoResponse filtrarParticipantePorApodo(Formulario.SWParticipante.filtrarParticipantePorApodoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWParticipante/filtrarParticipantePorApodoRequest", ReplyAction="http://ws/SWParticipante/filtrarParticipantePorApodoResponse")]
        System.Threading.Tasks.Task<Formulario.SWParticipante.filtrarParticipantePorApodoResponse> filtrarParticipantePorApodoAsync(Formulario.SWParticipante.filtrarParticipantePorApodoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWParticipante/eliminarParticipanteRequest", ReplyAction="http://ws/SWParticipante/eliminarParticipanteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Formulario.SWParticipante.eliminarParticipanteResponse eliminarParticipante(Formulario.SWParticipante.eliminarParticipanteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWParticipante/eliminarParticipanteRequest", ReplyAction="http://ws/SWParticipante/eliminarParticipanteResponse")]
        System.Threading.Tasks.Task<Formulario.SWParticipante.eliminarParticipanteResponse> eliminarParticipanteAsync(Formulario.SWParticipante.eliminarParticipanteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWParticipante/buscarParticipanteRequest", ReplyAction="http://ws/SWParticipante/buscarParticipanteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Formulario.SWParticipante.buscarParticipanteResponse buscarParticipante(Formulario.SWParticipante.buscarParticipanteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWParticipante/buscarParticipanteRequest", ReplyAction="http://ws/SWParticipante/buscarParticipanteResponse")]
        System.Threading.Tasks.Task<Formulario.SWParticipante.buscarParticipanteResponse> buscarParticipanteAsync(Formulario.SWParticipante.buscarParticipanteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWParticipante/listarPartidosDeUnParticipanteRequest", ReplyAction="http://ws/SWParticipante/listarPartidosDeUnParticipanteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Formulario.SWParticipante.listarPartidosDeUnParticipanteResponse listarPartidosDeUnParticipante(Formulario.SWParticipante.listarPartidosDeUnParticipanteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWParticipante/listarPartidosDeUnParticipanteRequest", ReplyAction="http://ws/SWParticipante/listarPartidosDeUnParticipanteResponse")]
        System.Threading.Tasks.Task<Formulario.SWParticipante.listarPartidosDeUnParticipanteResponse> listarPartidosDeUnParticipanteAsync(Formulario.SWParticipante.listarPartidosDeUnParticipanteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Estadisticas", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class EstadisticasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public EstadisticasRequest() {
        }
        
        public EstadisticasRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EstadisticasResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class EstadisticasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int>[] @return;
        
        public EstadisticasResponse() {
        }
        
        public EstadisticasResponse(System.Nullable<int>[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearParticipante", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class crearParticipanteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime arg3;
        
        public crearParticipanteRequest() {
        }
        
        public crearParticipanteRequest(int arg0, string arg1, System.DateTime arg2, System.DateTime arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearParticipanteResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class crearParticipanteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public crearParticipanteResponse() {
        }
        
        public crearParticipanteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class participante : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apodoField;
        
        private System.DateTime fechaCaducidadField;
        
        private bool fechaCaducidadFieldSpecified;
        
        private System.DateTime fechaInscripcionField;
        
        private bool fechaInscripcionFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apodo {
            get {
                return this.apodoField;
            }
            set {
                this.apodoField = value;
                this.RaisePropertyChanged("apodo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaCaducidad {
            get {
                return this.fechaCaducidadField;
            }
            set {
                this.fechaCaducidadField = value;
                this.RaisePropertyChanged("fechaCaducidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCaducidadSpecified {
            get {
                return this.fechaCaducidadFieldSpecified;
            }
            set {
                this.fechaCaducidadFieldSpecified = value;
                this.RaisePropertyChanged("fechaCaducidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaInscripcion {
            get {
                return this.fechaInscripcionField;
            }
            set {
                this.fechaInscripcionField = value;
                this.RaisePropertyChanged("fechaInscripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInscripcionSpecified {
            get {
                return this.fechaInscripcionFieldSpecified;
            }
            set {
                this.fechaInscripcionFieldSpecified = value;
                this.RaisePropertyChanged("fechaInscripcionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class partidoPK : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int mesaIdField;
        
        private int parcipante1Field;
        
        private int parcipante2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int mesaId {
            get {
                return this.mesaIdField;
            }
            set {
                this.mesaIdField = value;
                this.RaisePropertyChanged("mesaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int parcipante1 {
            get {
                return this.parcipante1Field;
            }
            set {
                this.parcipante1Field = value;
                this.RaisePropertyChanged("parcipante1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int parcipante2 {
            get {
                return this.parcipante2Field;
            }
            set {
                this.parcipante2Field = value;
                this.RaisePropertyChanged("parcipante2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class mesa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idMesaField;
        
        private bool idMesaFieldSpecified;
        
        private string localidadField;
        
        private string nombreLugarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idMesa {
            get {
                return this.idMesaField;
            }
            set {
                this.idMesaField = value;
                this.RaisePropertyChanged("idMesa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idMesaSpecified {
            get {
                return this.idMesaFieldSpecified;
            }
            set {
                this.idMesaFieldSpecified = value;
                this.RaisePropertyChanged("idMesaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
                this.RaisePropertyChanged("localidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombreLugar {
            get {
                return this.nombreLugarField;
            }
            set {
                this.nombreLugarField = value;
                this.RaisePropertyChanged("nombreLugar");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class partido : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaProgramadaField;
        
        private bool fechaProgramadaFieldSpecified;
        
        private int ganadorField;
        
        private System.DateTime horaFinField;
        
        private bool horaFinFieldSpecified;
        
        private System.DateTime horaInicioField;
        
        private bool horaInicioFieldSpecified;
        
        private mesa mesaField;
        
        private participante participanteField;
        
        private participante participante1Field;
        
        private partidoPK partidoPKField;
        
        private int rondaField;
        
        private string torneoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fechaProgramada {
            get {
                return this.fechaProgramadaField;
            }
            set {
                this.fechaProgramadaField = value;
                this.RaisePropertyChanged("fechaProgramada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaProgramadaSpecified {
            get {
                return this.fechaProgramadaFieldSpecified;
            }
            set {
                this.fechaProgramadaFieldSpecified = value;
                this.RaisePropertyChanged("fechaProgramadaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int ganador {
            get {
                return this.ganadorField;
            }
            set {
                this.ganadorField = value;
                this.RaisePropertyChanged("ganador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime horaFin {
            get {
                return this.horaFinField;
            }
            set {
                this.horaFinField = value;
                this.RaisePropertyChanged("horaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool horaFinSpecified {
            get {
                return this.horaFinFieldSpecified;
            }
            set {
                this.horaFinFieldSpecified = value;
                this.RaisePropertyChanged("horaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime horaInicio {
            get {
                return this.horaInicioField;
            }
            set {
                this.horaInicioField = value;
                this.RaisePropertyChanged("horaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool horaInicioSpecified {
            get {
                return this.horaInicioFieldSpecified;
            }
            set {
                this.horaInicioFieldSpecified = value;
                this.RaisePropertyChanged("horaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public mesa mesa {
            get {
                return this.mesaField;
            }
            set {
                this.mesaField = value;
                this.RaisePropertyChanged("mesa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public participante participante {
            get {
                return this.participanteField;
            }
            set {
                this.participanteField = value;
                this.RaisePropertyChanged("participante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public participante participante1 {
            get {
                return this.participante1Field;
            }
            set {
                this.participante1Field = value;
                this.RaisePropertyChanged("participante1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public partidoPK partidoPK {
            get {
                return this.partidoPKField;
            }
            set {
                this.partidoPKField = value;
                this.RaisePropertyChanged("partidoPK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int ronda {
            get {
                return this.rondaField;
            }
            set {
                this.rondaField = value;
                this.RaisePropertyChanged("ronda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string torneo {
            get {
                return this.torneoField;
            }
            set {
                this.torneoField = value;
                this.RaisePropertyChanged("torneo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarParticipantes", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class listarParticipantesRequest {
        
        public listarParticipantesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarParticipantesResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class listarParticipantesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Formulario.SWParticipante.participante[] @return;
        
        public listarParticipantesResponse() {
        }
        
        public listarParticipantesResponse(Formulario.SWParticipante.participante[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarParticipante", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class actualizarParticipanteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime arg3;
        
        public actualizarParticipanteRequest() {
        }
        
        public actualizarParticipanteRequest(int arg0, string arg1, System.DateTime arg2, System.DateTime arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarParticipanteResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class actualizarParticipanteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarParticipanteResponse() {
        }
        
        public actualizarParticipanteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="filtrarParticipantePorApodo", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class filtrarParticipantePorApodoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public filtrarParticipantePorApodoRequest() {
        }
        
        public filtrarParticipantePorApodoRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="filtrarParticipantePorApodoResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class filtrarParticipantePorApodoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Formulario.SWParticipante.participante[] @return;
        
        public filtrarParticipantePorApodoResponse() {
        }
        
        public filtrarParticipantePorApodoResponse(Formulario.SWParticipante.participante[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarParticipante", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class eliminarParticipanteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime arg3;
        
        public eliminarParticipanteRequest() {
        }
        
        public eliminarParticipanteRequest(int arg0, string arg1, System.DateTime arg2, System.DateTime arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarParticipanteResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class eliminarParticipanteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarParticipanteResponse() {
        }
        
        public eliminarParticipanteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarParticipante", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class buscarParticipanteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public buscarParticipanteRequest() {
        }
        
        public buscarParticipanteRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarParticipanteResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class buscarParticipanteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Formulario.SWParticipante.participante @return;
        
        public buscarParticipanteResponse() {
        }
        
        public buscarParticipanteResponse(Formulario.SWParticipante.participante @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPartidosDeUnParticipante", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class listarPartidosDeUnParticipanteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public listarPartidosDeUnParticipanteRequest() {
        }
        
        public listarPartidosDeUnParticipanteRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPartidosDeUnParticipanteResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class listarPartidosDeUnParticipanteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Formulario.SWParticipante.partido[] @return;
        
        public listarPartidosDeUnParticipanteResponse() {
        }
        
        public listarPartidosDeUnParticipanteResponse(Formulario.SWParticipante.partido[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SWParticipanteChannel : Formulario.SWParticipante.SWParticipante, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SWParticipanteClient : System.ServiceModel.ClientBase<Formulario.SWParticipante.SWParticipante>, Formulario.SWParticipante.SWParticipante {
        
        public SWParticipanteClient() {
        }
        
        public SWParticipanteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SWParticipanteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWParticipanteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWParticipanteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formulario.SWParticipante.helloResponse Formulario.SWParticipante.SWParticipante.hello(Formulario.SWParticipante.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            Formulario.SWParticipante.helloRequest inValue = new Formulario.SWParticipante.helloRequest();
            inValue.name = name;
            Formulario.SWParticipante.helloResponse retVal = ((Formulario.SWParticipante.SWParticipante)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formulario.SWParticipante.helloResponse> Formulario.SWParticipante.SWParticipante.helloAsync(Formulario.SWParticipante.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formulario.SWParticipante.helloResponse> helloAsync(string name) {
            Formulario.SWParticipante.helloRequest inValue = new Formulario.SWParticipante.helloRequest();
            inValue.name = name;
            return ((Formulario.SWParticipante.SWParticipante)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formulario.SWParticipante.EstadisticasResponse Formulario.SWParticipante.SWParticipante.Estadisticas(Formulario.SWParticipante.EstadisticasRequest request) {
            return base.Channel.Estadisticas(request);
        }
        
        public System.Nullable<int>[] Estadisticas(int arg0) {
            Formulario.SWParticipante.EstadisticasRequest inValue = new Formulario.SWParticipante.EstadisticasRequest();
            inValue.arg0 = arg0;
            Formulario.SWParticipante.EstadisticasResponse retVal = ((Formulario.SWParticipante.SWParticipante)(this)).Estadisticas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formulario.SWParticipante.EstadisticasResponse> Formulario.SWParticipante.SWParticipante.EstadisticasAsync(Formulario.SWParticipante.EstadisticasRequest request) {
            return base.Channel.EstadisticasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formulario.SWParticipante.EstadisticasResponse> EstadisticasAsync(int arg0) {
            Formulario.SWParticipante.EstadisticasRequest inValue = new Formulario.SWParticipante.EstadisticasRequest();
            inValue.arg0 = arg0;
            return ((Formulario.SWParticipante.SWParticipante)(this)).EstadisticasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formulario.SWParticipante.crearParticipanteResponse Formulario.SWParticipante.SWParticipante.crearParticipante(Formulario.SWParticipante.crearParticipanteRequest request) {
            return base.Channel.crearParticipante(request);
        }
        
        public int crearParticipante(int arg0, string arg1, System.DateTime arg2, System.DateTime arg3) {
            Formulario.SWParticipante.crearParticipanteRequest inValue = new Formulario.SWParticipante.crearParticipanteRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            Formulario.SWParticipante.crearParticipanteResponse retVal = ((Formulario.SWParticipante.SWParticipante)(this)).crearParticipante(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formulario.SWParticipante.crearParticipanteResponse> Formulario.SWParticipante.SWParticipante.crearParticipanteAsync(Formulario.SWParticipante.crearParticipanteRequest request) {
            return base.Channel.crearParticipanteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formulario.SWParticipante.crearParticipanteResponse> crearParticipanteAsync(int arg0, string arg1, System.DateTime arg2, System.DateTime arg3) {
            Formulario.SWParticipante.crearParticipanteRequest inValue = new Formulario.SWParticipante.crearParticipanteRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((Formulario.SWParticipante.SWParticipante)(this)).crearParticipanteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formulario.SWParticipante.listarParticipantesResponse Formulario.SWParticipante.SWParticipante.listarParticipantes(Formulario.SWParticipante.listarParticipantesRequest request) {
            return base.Channel.listarParticipantes(request);
        }
        
        public Formulario.SWParticipante.participante[] listarParticipantes() {
            Formulario.SWParticipante.listarParticipantesRequest inValue = new Formulario.SWParticipante.listarParticipantesRequest();
            Formulario.SWParticipante.listarParticipantesResponse retVal = ((Formulario.SWParticipante.SWParticipante)(this)).listarParticipantes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formulario.SWParticipante.listarParticipantesResponse> Formulario.SWParticipante.SWParticipante.listarParticipantesAsync(Formulario.SWParticipante.listarParticipantesRequest request) {
            return base.Channel.listarParticipantesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formulario.SWParticipante.listarParticipantesResponse> listarParticipantesAsync() {
            Formulario.SWParticipante.listarParticipantesRequest inValue = new Formulario.SWParticipante.listarParticipantesRequest();
            return ((Formulario.SWParticipante.SWParticipante)(this)).listarParticipantesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formulario.SWParticipante.actualizarParticipanteResponse Formulario.SWParticipante.SWParticipante.actualizarParticipante(Formulario.SWParticipante.actualizarParticipanteRequest request) {
            return base.Channel.actualizarParticipante(request);
        }
        
        public int actualizarParticipante(int arg0, string arg1, System.DateTime arg2, System.DateTime arg3) {
            Formulario.SWParticipante.actualizarParticipanteRequest inValue = new Formulario.SWParticipante.actualizarParticipanteRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            Formulario.SWParticipante.actualizarParticipanteResponse retVal = ((Formulario.SWParticipante.SWParticipante)(this)).actualizarParticipante(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formulario.SWParticipante.actualizarParticipanteResponse> Formulario.SWParticipante.SWParticipante.actualizarParticipanteAsync(Formulario.SWParticipante.actualizarParticipanteRequest request) {
            return base.Channel.actualizarParticipanteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formulario.SWParticipante.actualizarParticipanteResponse> actualizarParticipanteAsync(int arg0, string arg1, System.DateTime arg2, System.DateTime arg3) {
            Formulario.SWParticipante.actualizarParticipanteRequest inValue = new Formulario.SWParticipante.actualizarParticipanteRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((Formulario.SWParticipante.SWParticipante)(this)).actualizarParticipanteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formulario.SWParticipante.filtrarParticipantePorApodoResponse Formulario.SWParticipante.SWParticipante.filtrarParticipantePorApodo(Formulario.SWParticipante.filtrarParticipantePorApodoRequest request) {
            return base.Channel.filtrarParticipantePorApodo(request);
        }
        
        public Formulario.SWParticipante.participante[] filtrarParticipantePorApodo(string arg0) {
            Formulario.SWParticipante.filtrarParticipantePorApodoRequest inValue = new Formulario.SWParticipante.filtrarParticipantePorApodoRequest();
            inValue.arg0 = arg0;
            Formulario.SWParticipante.filtrarParticipantePorApodoResponse retVal = ((Formulario.SWParticipante.SWParticipante)(this)).filtrarParticipantePorApodo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formulario.SWParticipante.filtrarParticipantePorApodoResponse> Formulario.SWParticipante.SWParticipante.filtrarParticipantePorApodoAsync(Formulario.SWParticipante.filtrarParticipantePorApodoRequest request) {
            return base.Channel.filtrarParticipantePorApodoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formulario.SWParticipante.filtrarParticipantePorApodoResponse> filtrarParticipantePorApodoAsync(string arg0) {
            Formulario.SWParticipante.filtrarParticipantePorApodoRequest inValue = new Formulario.SWParticipante.filtrarParticipantePorApodoRequest();
            inValue.arg0 = arg0;
            return ((Formulario.SWParticipante.SWParticipante)(this)).filtrarParticipantePorApodoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formulario.SWParticipante.eliminarParticipanteResponse Formulario.SWParticipante.SWParticipante.eliminarParticipante(Formulario.SWParticipante.eliminarParticipanteRequest request) {
            return base.Channel.eliminarParticipante(request);
        }
        
        public int eliminarParticipante(int arg0, string arg1, System.DateTime arg2, System.DateTime arg3) {
            Formulario.SWParticipante.eliminarParticipanteRequest inValue = new Formulario.SWParticipante.eliminarParticipanteRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            Formulario.SWParticipante.eliminarParticipanteResponse retVal = ((Formulario.SWParticipante.SWParticipante)(this)).eliminarParticipante(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formulario.SWParticipante.eliminarParticipanteResponse> Formulario.SWParticipante.SWParticipante.eliminarParticipanteAsync(Formulario.SWParticipante.eliminarParticipanteRequest request) {
            return base.Channel.eliminarParticipanteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formulario.SWParticipante.eliminarParticipanteResponse> eliminarParticipanteAsync(int arg0, string arg1, System.DateTime arg2, System.DateTime arg3) {
            Formulario.SWParticipante.eliminarParticipanteRequest inValue = new Formulario.SWParticipante.eliminarParticipanteRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((Formulario.SWParticipante.SWParticipante)(this)).eliminarParticipanteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formulario.SWParticipante.buscarParticipanteResponse Formulario.SWParticipante.SWParticipante.buscarParticipante(Formulario.SWParticipante.buscarParticipanteRequest request) {
            return base.Channel.buscarParticipante(request);
        }
        
        public Formulario.SWParticipante.participante buscarParticipante(int arg0) {
            Formulario.SWParticipante.buscarParticipanteRequest inValue = new Formulario.SWParticipante.buscarParticipanteRequest();
            inValue.arg0 = arg0;
            Formulario.SWParticipante.buscarParticipanteResponse retVal = ((Formulario.SWParticipante.SWParticipante)(this)).buscarParticipante(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formulario.SWParticipante.buscarParticipanteResponse> Formulario.SWParticipante.SWParticipante.buscarParticipanteAsync(Formulario.SWParticipante.buscarParticipanteRequest request) {
            return base.Channel.buscarParticipanteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formulario.SWParticipante.buscarParticipanteResponse> buscarParticipanteAsync(int arg0) {
            Formulario.SWParticipante.buscarParticipanteRequest inValue = new Formulario.SWParticipante.buscarParticipanteRequest();
            inValue.arg0 = arg0;
            return ((Formulario.SWParticipante.SWParticipante)(this)).buscarParticipanteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formulario.SWParticipante.listarPartidosDeUnParticipanteResponse Formulario.SWParticipante.SWParticipante.listarPartidosDeUnParticipante(Formulario.SWParticipante.listarPartidosDeUnParticipanteRequest request) {
            return base.Channel.listarPartidosDeUnParticipante(request);
        }
        
        public Formulario.SWParticipante.partido[] listarPartidosDeUnParticipante(int arg0) {
            Formulario.SWParticipante.listarPartidosDeUnParticipanteRequest inValue = new Formulario.SWParticipante.listarPartidosDeUnParticipanteRequest();
            inValue.arg0 = arg0;
            Formulario.SWParticipante.listarPartidosDeUnParticipanteResponse retVal = ((Formulario.SWParticipante.SWParticipante)(this)).listarPartidosDeUnParticipante(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formulario.SWParticipante.listarPartidosDeUnParticipanteResponse> Formulario.SWParticipante.SWParticipante.listarPartidosDeUnParticipanteAsync(Formulario.SWParticipante.listarPartidosDeUnParticipanteRequest request) {
            return base.Channel.listarPartidosDeUnParticipanteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formulario.SWParticipante.listarPartidosDeUnParticipanteResponse> listarPartidosDeUnParticipanteAsync(int arg0) {
            Formulario.SWParticipante.listarPartidosDeUnParticipanteRequest inValue = new Formulario.SWParticipante.listarPartidosDeUnParticipanteRequest();
            inValue.arg0 = arg0;
            return ((Formulario.SWParticipante.SWParticipante)(this)).listarPartidosDeUnParticipanteAsync(inValue);
        }
    }
}
