//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formulario.ServiceMesa {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="ServiceMesa.SWmesa")]
    public interface SWmesa {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWmesa/listarMesasRequest", ReplyAction="http://ws/SWmesa/listarMesasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Formulario.ServiceMesa.listarMesasResponse listarMesas(Formulario.ServiceMesa.listarMesasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWmesa/listarMesasRequest", ReplyAction="http://ws/SWmesa/listarMesasResponse")]
        System.Threading.Tasks.Task<Formulario.ServiceMesa.listarMesasResponse> listarMesasAsync(Formulario.ServiceMesa.listarMesasRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class mesa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idMesaField;
        
        private bool idMesaFieldSpecified;
        
        private string localidadField;
        
        private string nombreLugarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idMesa {
            get {
                return this.idMesaField;
            }
            set {
                this.idMesaField = value;
                this.RaisePropertyChanged("idMesa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idMesaSpecified {
            get {
                return this.idMesaFieldSpecified;
            }
            set {
                this.idMesaFieldSpecified = value;
                this.RaisePropertyChanged("idMesaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
                this.RaisePropertyChanged("localidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombreLugar {
            get {
                return this.nombreLugarField;
            }
            set {
                this.nombreLugarField = value;
                this.RaisePropertyChanged("nombreLugar");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMesas", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class listarMesasRequest {
        
        public listarMesasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMesasResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class listarMesasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Formulario.ServiceMesa.mesa[] @return;
        
        public listarMesasResponse() {
        }
        
        public listarMesasResponse(Formulario.ServiceMesa.mesa[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SWmesaChannel : Formulario.ServiceMesa.SWmesa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SWmesaClient : System.ServiceModel.ClientBase<Formulario.ServiceMesa.SWmesa>, Formulario.ServiceMesa.SWmesa {
        
        public SWmesaClient() {
        }
        
        public SWmesaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SWmesaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWmesaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWmesaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formulario.ServiceMesa.listarMesasResponse Formulario.ServiceMesa.SWmesa.listarMesas(Formulario.ServiceMesa.listarMesasRequest request) {
            return base.Channel.listarMesas(request);
        }
        
        public Formulario.ServiceMesa.mesa[] listarMesas() {
            Formulario.ServiceMesa.listarMesasRequest inValue = new Formulario.ServiceMesa.listarMesasRequest();
            Formulario.ServiceMesa.listarMesasResponse retVal = ((Formulario.ServiceMesa.SWmesa)(this)).listarMesas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formulario.ServiceMesa.listarMesasResponse> Formulario.ServiceMesa.SWmesa.listarMesasAsync(Formulario.ServiceMesa.listarMesasRequest request) {
            return base.Channel.listarMesasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formulario.ServiceMesa.listarMesasResponse> listarMesasAsync() {
            Formulario.ServiceMesa.listarMesasRequest inValue = new Formulario.ServiceMesa.listarMesasRequest();
            return ((Formulario.ServiceMesa.SWmesa)(this)).listarMesasAsync(inValue);
        }
    }
}
