//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formulario.SWPartido {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="SWPartido.SWPartido")]
    public interface SWPartido {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWPartido/crearPartidoRequest", ReplyAction="http://ws/SWPartido/crearPartidoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Formulario.SWPartido.crearPartidoResponse crearPartido(Formulario.SWPartido.crearPartidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWPartido/crearPartidoRequest", ReplyAction="http://ws/SWPartido/crearPartidoResponse")]
        System.Threading.Tasks.Task<Formulario.SWPartido.crearPartidoResponse> crearPartidoAsync(Formulario.SWPartido.crearPartidoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWPartido/listarPorIdRequest", ReplyAction="http://ws/SWPartido/listarPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Formulario.SWPartido.listarPorIdResponse listarPorId(Formulario.SWPartido.listarPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWPartido/listarPorIdRequest", ReplyAction="http://ws/SWPartido/listarPorIdResponse")]
        System.Threading.Tasks.Task<Formulario.SWPartido.listarPorIdResponse> listarPorIdAsync(Formulario.SWPartido.listarPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWPartido/helloRequest", ReplyAction="http://ws/SWPartido/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Formulario.SWPartido.helloResponse hello(Formulario.SWPartido.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWPartido/helloRequest", ReplyAction="http://ws/SWPartido/helloResponse")]
        System.Threading.Tasks.Task<Formulario.SWPartido.helloResponse> helloAsync(Formulario.SWPartido.helloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWPartido/eliminarPartidoRequest", ReplyAction="http://ws/SWPartido/eliminarPartidoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Formulario.SWPartido.eliminarPartidoResponse eliminarPartido(Formulario.SWPartido.eliminarPartidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWPartido/eliminarPartidoRequest", ReplyAction="http://ws/SWPartido/eliminarPartidoResponse")]
        System.Threading.Tasks.Task<Formulario.SWPartido.eliminarPartidoResponse> eliminarPartidoAsync(Formulario.SWPartido.eliminarPartidoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWPartido/actualizarPartidoRequest", ReplyAction="http://ws/SWPartido/actualizarPartidoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Formulario.SWPartido.actualizarPartidoResponse actualizarPartido(Formulario.SWPartido.actualizarPartidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWPartido/actualizarPartidoRequest", ReplyAction="http://ws/SWPartido/actualizarPartidoResponse")]
        System.Threading.Tasks.Task<Formulario.SWPartido.actualizarPartidoResponse> actualizarPartidoAsync(Formulario.SWPartido.actualizarPartidoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWPartido/listarTodosLosPartidosRequest", ReplyAction="http://ws/SWPartido/listarTodosLosPartidosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Formulario.SWPartido.listarTodosLosPartidosResponse listarTodosLosPartidos(Formulario.SWPartido.listarTodosLosPartidosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/SWPartido/listarTodosLosPartidosRequest", ReplyAction="http://ws/SWPartido/listarTodosLosPartidosResponse")]
        System.Threading.Tasks.Task<Formulario.SWPartido.listarTodosLosPartidosResponse> listarTodosLosPartidosAsync(Formulario.SWPartido.listarTodosLosPartidosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearPartido", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class crearPartidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime arg5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime arg6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime arg7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg8;
        
        public crearPartidoRequest() {
        }
        
        public crearPartidoRequest(int arg0, int arg1, int arg2, int arg3, int arg4, System.DateTime arg5, System.DateTime arg6, System.DateTime arg7, string arg8) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
            this.arg8 = arg8;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearPartidoResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class crearPartidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public crearPartidoResponse() {
        }
        
        public crearPartidoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class partido : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaProgramadaField;
        
        private bool fechaProgramadaFieldSpecified;
        
        private int ganadorField;
        
        private System.DateTime horaFinField;
        
        private bool horaFinFieldSpecified;
        
        private System.DateTime horaInicioField;
        
        private bool horaInicioFieldSpecified;
        
        private mesa mesaField;
        
        private participante participanteField;
        
        private participante participante1Field;
        
        private partidoPK partidoPKField;
        
        private int rondaField;
        
        private string torneoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fechaProgramada {
            get {
                return this.fechaProgramadaField;
            }
            set {
                this.fechaProgramadaField = value;
                this.RaisePropertyChanged("fechaProgramada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaProgramadaSpecified {
            get {
                return this.fechaProgramadaFieldSpecified;
            }
            set {
                this.fechaProgramadaFieldSpecified = value;
                this.RaisePropertyChanged("fechaProgramadaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int ganador {
            get {
                return this.ganadorField;
            }
            set {
                this.ganadorField = value;
                this.RaisePropertyChanged("ganador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime horaFin {
            get {
                return this.horaFinField;
            }
            set {
                this.horaFinField = value;
                this.RaisePropertyChanged("horaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool horaFinSpecified {
            get {
                return this.horaFinFieldSpecified;
            }
            set {
                this.horaFinFieldSpecified = value;
                this.RaisePropertyChanged("horaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime horaInicio {
            get {
                return this.horaInicioField;
            }
            set {
                this.horaInicioField = value;
                this.RaisePropertyChanged("horaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool horaInicioSpecified {
            get {
                return this.horaInicioFieldSpecified;
            }
            set {
                this.horaInicioFieldSpecified = value;
                this.RaisePropertyChanged("horaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public mesa mesa {
            get {
                return this.mesaField;
            }
            set {
                this.mesaField = value;
                this.RaisePropertyChanged("mesa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public participante participante {
            get {
                return this.participanteField;
            }
            set {
                this.participanteField = value;
                this.RaisePropertyChanged("participante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public participante participante1 {
            get {
                return this.participante1Field;
            }
            set {
                this.participante1Field = value;
                this.RaisePropertyChanged("participante1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public partidoPK partidoPK {
            get {
                return this.partidoPKField;
            }
            set {
                this.partidoPKField = value;
                this.RaisePropertyChanged("partidoPK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int ronda {
            get {
                return this.rondaField;
            }
            set {
                this.rondaField = value;
                this.RaisePropertyChanged("ronda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string torneo {
            get {
                return this.torneoField;
            }
            set {
                this.torneoField = value;
                this.RaisePropertyChanged("torneo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class mesa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idMesaField;
        
        private bool idMesaFieldSpecified;
        
        private string localidadField;
        
        private string nombreLugarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idMesa {
            get {
                return this.idMesaField;
            }
            set {
                this.idMesaField = value;
                this.RaisePropertyChanged("idMesa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idMesaSpecified {
            get {
                return this.idMesaFieldSpecified;
            }
            set {
                this.idMesaFieldSpecified = value;
                this.RaisePropertyChanged("idMesaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
                this.RaisePropertyChanged("localidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombreLugar {
            get {
                return this.nombreLugarField;
            }
            set {
                this.nombreLugarField = value;
                this.RaisePropertyChanged("nombreLugar");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class partidoPK : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int mesaIdField;
        
        private int parcipante1Field;
        
        private int parcipante2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int mesaId {
            get {
                return this.mesaIdField;
            }
            set {
                this.mesaIdField = value;
                this.RaisePropertyChanged("mesaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int parcipante1 {
            get {
                return this.parcipante1Field;
            }
            set {
                this.parcipante1Field = value;
                this.RaisePropertyChanged("parcipante1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int parcipante2 {
            get {
                return this.parcipante2Field;
            }
            set {
                this.parcipante2Field = value;
                this.RaisePropertyChanged("parcipante2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class participante : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apodoField;
        
        private System.DateTime fechaCaducidadField;
        
        private bool fechaCaducidadFieldSpecified;
        
        private System.DateTime fechaInscripcionField;
        
        private bool fechaInscripcionFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apodo {
            get {
                return this.apodoField;
            }
            set {
                this.apodoField = value;
                this.RaisePropertyChanged("apodo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaCaducidad {
            get {
                return this.fechaCaducidadField;
            }
            set {
                this.fechaCaducidadField = value;
                this.RaisePropertyChanged("fechaCaducidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCaducidadSpecified {
            get {
                return this.fechaCaducidadFieldSpecified;
            }
            set {
                this.fechaCaducidadFieldSpecified = value;
                this.RaisePropertyChanged("fechaCaducidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaInscripcion {
            get {
                return this.fechaInscripcionField;
            }
            set {
                this.fechaInscripcionField = value;
                this.RaisePropertyChanged("fechaInscripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInscripcionSpecified {
            get {
                return this.fechaInscripcionFieldSpecified;
            }
            set {
                this.fechaInscripcionFieldSpecified = value;
                this.RaisePropertyChanged("fechaInscripcionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorId", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class listarPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arq0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        public listarPorIdRequest() {
        }
        
        public listarPorIdRequest(int arq0, int arg1, int arg2) {
            this.arq0 = arq0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorIdResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class listarPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Formulario.SWPartido.partido[] @return;
        
        public listarPorIdResponse() {
        }
        
        public listarPorIdResponse(Formulario.SWPartido.partido[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPartido", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class eliminarPartidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        public eliminarPartidoRequest() {
        }
        
        public eliminarPartidoRequest(int arg0, int arg1, int arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPartidoResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class eliminarPartidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarPartidoResponse() {
        }
        
        public eliminarPartidoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarPartido", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class actualizarPartidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime arg5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime arg6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime arg7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg8;
        
        public actualizarPartidoRequest() {
        }
        
        public actualizarPartidoRequest(int arg0, int arg1, int arg2, int arg3, int arg4, System.DateTime arg5, System.DateTime arg6, System.DateTime arg7, string arg8) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
            this.arg8 = arg8;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarPartidoResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class actualizarPartidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarPartidoResponse() {
        }
        
        public actualizarPartidoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosLosPartidos", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class listarTodosLosPartidosRequest {
        
        public listarTodosLosPartidosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosLosPartidosResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class listarTodosLosPartidosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Formulario.SWPartido.partido[] @return;
        
        public listarTodosLosPartidosResponse() {
        }
        
        public listarTodosLosPartidosResponse(Formulario.SWPartido.partido[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SWPartidoChannel : Formulario.SWPartido.SWPartido, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SWPartidoClient : System.ServiceModel.ClientBase<Formulario.SWPartido.SWPartido>, Formulario.SWPartido.SWPartido {
        
        public SWPartidoClient() {
        }
        
        public SWPartidoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SWPartidoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWPartidoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWPartidoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formulario.SWPartido.crearPartidoResponse Formulario.SWPartido.SWPartido.crearPartido(Formulario.SWPartido.crearPartidoRequest request) {
            return base.Channel.crearPartido(request);
        }
        
        public int crearPartido(int arg0, int arg1, int arg2, int arg3, int arg4, System.DateTime arg5, System.DateTime arg6, System.DateTime arg7, string arg8) {
            Formulario.SWPartido.crearPartidoRequest inValue = new Formulario.SWPartido.crearPartidoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            Formulario.SWPartido.crearPartidoResponse retVal = ((Formulario.SWPartido.SWPartido)(this)).crearPartido(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formulario.SWPartido.crearPartidoResponse> Formulario.SWPartido.SWPartido.crearPartidoAsync(Formulario.SWPartido.crearPartidoRequest request) {
            return base.Channel.crearPartidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formulario.SWPartido.crearPartidoResponse> crearPartidoAsync(int arg0, int arg1, int arg2, int arg3, int arg4, System.DateTime arg5, System.DateTime arg6, System.DateTime arg7, string arg8) {
            Formulario.SWPartido.crearPartidoRequest inValue = new Formulario.SWPartido.crearPartidoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            return ((Formulario.SWPartido.SWPartido)(this)).crearPartidoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formulario.SWPartido.listarPorIdResponse Formulario.SWPartido.SWPartido.listarPorId(Formulario.SWPartido.listarPorIdRequest request) {
            return base.Channel.listarPorId(request);
        }
        
        public Formulario.SWPartido.partido[] listarPorId(int arq0, int arg1, int arg2) {
            Formulario.SWPartido.listarPorIdRequest inValue = new Formulario.SWPartido.listarPorIdRequest();
            inValue.arq0 = arq0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            Formulario.SWPartido.listarPorIdResponse retVal = ((Formulario.SWPartido.SWPartido)(this)).listarPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formulario.SWPartido.listarPorIdResponse> Formulario.SWPartido.SWPartido.listarPorIdAsync(Formulario.SWPartido.listarPorIdRequest request) {
            return base.Channel.listarPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formulario.SWPartido.listarPorIdResponse> listarPorIdAsync(int arq0, int arg1, int arg2) {
            Formulario.SWPartido.listarPorIdRequest inValue = new Formulario.SWPartido.listarPorIdRequest();
            inValue.arq0 = arq0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((Formulario.SWPartido.SWPartido)(this)).listarPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formulario.SWPartido.helloResponse Formulario.SWPartido.SWPartido.hello(Formulario.SWPartido.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            Formulario.SWPartido.helloRequest inValue = new Formulario.SWPartido.helloRequest();
            inValue.name = name;
            Formulario.SWPartido.helloResponse retVal = ((Formulario.SWPartido.SWPartido)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formulario.SWPartido.helloResponse> Formulario.SWPartido.SWPartido.helloAsync(Formulario.SWPartido.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formulario.SWPartido.helloResponse> helloAsync(string name) {
            Formulario.SWPartido.helloRequest inValue = new Formulario.SWPartido.helloRequest();
            inValue.name = name;
            return ((Formulario.SWPartido.SWPartido)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formulario.SWPartido.eliminarPartidoResponse Formulario.SWPartido.SWPartido.eliminarPartido(Formulario.SWPartido.eliminarPartidoRequest request) {
            return base.Channel.eliminarPartido(request);
        }
        
        public int eliminarPartido(int arg0, int arg1, int arg2) {
            Formulario.SWPartido.eliminarPartidoRequest inValue = new Formulario.SWPartido.eliminarPartidoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            Formulario.SWPartido.eliminarPartidoResponse retVal = ((Formulario.SWPartido.SWPartido)(this)).eliminarPartido(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formulario.SWPartido.eliminarPartidoResponse> Formulario.SWPartido.SWPartido.eliminarPartidoAsync(Formulario.SWPartido.eliminarPartidoRequest request) {
            return base.Channel.eliminarPartidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formulario.SWPartido.eliminarPartidoResponse> eliminarPartidoAsync(int arg0, int arg1, int arg2) {
            Formulario.SWPartido.eliminarPartidoRequest inValue = new Formulario.SWPartido.eliminarPartidoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((Formulario.SWPartido.SWPartido)(this)).eliminarPartidoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formulario.SWPartido.actualizarPartidoResponse Formulario.SWPartido.SWPartido.actualizarPartido(Formulario.SWPartido.actualizarPartidoRequest request) {
            return base.Channel.actualizarPartido(request);
        }
        
        public int actualizarPartido(int arg0, int arg1, int arg2, int arg3, int arg4, System.DateTime arg5, System.DateTime arg6, System.DateTime arg7, string arg8) {
            Formulario.SWPartido.actualizarPartidoRequest inValue = new Formulario.SWPartido.actualizarPartidoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            Formulario.SWPartido.actualizarPartidoResponse retVal = ((Formulario.SWPartido.SWPartido)(this)).actualizarPartido(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formulario.SWPartido.actualizarPartidoResponse> Formulario.SWPartido.SWPartido.actualizarPartidoAsync(Formulario.SWPartido.actualizarPartidoRequest request) {
            return base.Channel.actualizarPartidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formulario.SWPartido.actualizarPartidoResponse> actualizarPartidoAsync(int arg0, int arg1, int arg2, int arg3, int arg4, System.DateTime arg5, System.DateTime arg6, System.DateTime arg7, string arg8) {
            Formulario.SWPartido.actualizarPartidoRequest inValue = new Formulario.SWPartido.actualizarPartidoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            return ((Formulario.SWPartido.SWPartido)(this)).actualizarPartidoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formulario.SWPartido.listarTodosLosPartidosResponse Formulario.SWPartido.SWPartido.listarTodosLosPartidos(Formulario.SWPartido.listarTodosLosPartidosRequest request) {
            return base.Channel.listarTodosLosPartidos(request);
        }
        
        public Formulario.SWPartido.partido[] listarTodosLosPartidos() {
            Formulario.SWPartido.listarTodosLosPartidosRequest inValue = new Formulario.SWPartido.listarTodosLosPartidosRequest();
            Formulario.SWPartido.listarTodosLosPartidosResponse retVal = ((Formulario.SWPartido.SWPartido)(this)).listarTodosLosPartidos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formulario.SWPartido.listarTodosLosPartidosResponse> Formulario.SWPartido.SWPartido.listarTodosLosPartidosAsync(Formulario.SWPartido.listarTodosLosPartidosRequest request) {
            return base.Channel.listarTodosLosPartidosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formulario.SWPartido.listarTodosLosPartidosResponse> listarTodosLosPartidosAsync() {
            Formulario.SWPartido.listarTodosLosPartidosRequest inValue = new Formulario.SWPartido.listarTodosLosPartidosRequest();
            return ((Formulario.SWPartido.SWPartido)(this)).listarTodosLosPartidosAsync(inValue);
        }
    }
}
